# Generated by Django 4.2.2 on 2023-07-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='is_charged',
            field=models.BooleanField(default=False),
        ),
    ]
