# Generated by Django 4.2.2 on 2023-07-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0003_rename_is_charged_subtitle_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='created',
            new_name='created_at',
        ),
    ]
